### ISSUE TITLE
PHP dependency

### ISSUE THREAD

**Issue by erfanimani** [geerlingguy/ansible-role-blackfire#1]
Firstly, thank you for your hard work on these Ansible roles. Now, this role has a dependency on your PHP role, but as far as I can see, there is nothing in the blackfire role that explicitly requires geerlingguy/ansible-role-php and I think it would be beneficial if these weren't coupled (I'm using a different PHP role). Thoughts?

**Comment by geerlingguy** [comment]
I do call two handlers that are set up and run by the `geerlingguy.php` role: https://github.com/geerlingguy/ansible-role-blackfire/blob/master/tasks/main.yml#L12-L14

**Comment by erfanimani** [comment]
True - all good. I guess I see notifications more like events which handlers might or might not listen to (as opposed to a hard dependency).
