### ISSUE TITLE
Restart blackfire-agent

### ISSUE THREAD

**Issue by jamesrward** [geerlingguy/ansible-role-blackfire#2]
After following the instruction any attempt to profile resulted in the following error:

```
Are you authorized to profile this page? No probe response, missing PHP extension or invalid signature for relaying agent.
```

A quick restart of the blackfire-agent solved the issue:

```
sudo /etc/init.d/blackfire-agent restart
```

I recommend adding this to the readme.

**Comment by khalidumarr** [comment]
worked fine for me, Thanks
